export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const CAMPAIGN_FETCH = 'CAMPAIGN_FETCH'
export const CAMPAIGN_SAVE = 'CAMPAIGN_SAVE'

export const INFLUENCER_FETCH = 'INFLUENCER_FETCH'
export const INFLUENCER_SAVE = 'INFLUENCER_SAVE'